name: Setup Action
description: Set up the project and install dependencies
runs:
  using: "composite"
  steps:
    - run: corepack enable
      shell: bash

    - uses: actions/setup-node@v4
      with:
        node-version: "22"
        cache: "pnpm"

    - run: pnpm install --frozen-lockfile
      shell: bash
